smallrye.jwt.sign.key.location=classpath:privateKey.pem
mp.jwt.verify.publickey.location=classpath:publicKey.pem

# Database configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=ROOT
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkusapp

quarkus.hibernate-orm.schema-management.strategy=none
quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.change-log=db/changeLog.xml

#quarkus.log.level=DEBUG

mp.jwt.verify.issuer=quarkus-auth
quarkus.log.category."io.quarkus.security".level=DEBUG
quarkus.log.category."io.smallrye.jwt".level=DEBUG