GET /auth/auto-login HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJxdWFya3VzLWF1dGgiLCJzdWIiOiJzdXJhaiIsImdyb3VwcyI6WyJVU0VSIl0sImlhdCI6MTc4ODI3ODQ3NiwiZXhwIjoxNzg4Mjc5Mzc2LCJqdGkiOiIyODg1NjlmZi00MzYyLTRlYjktODkwNi01NGQwOWQ3ZWQ3NTMifQ.MTe1RFjrmQ8BwUo9ccHDsC8qvY-6qzKJUu5ywB4D55iD5TPnbxRCIH2qeb0rGrrJH8-VucLTyKY5ookFs9NSxlMlqOpyO5kbzn_Ubz1EF1bSFm3mJTus5YLkmAjWmchaMKUM2iEc_f64XAki1HCfwSl0I_dh8Q4C63EO6VFzTXbPimMhHaSXpzcRkUPhIUS9wZyIQbf_1cFkJHcWSDr0yl6279idCmyQtOTb-5w3V51CmdQ_b93Wo5sUQZ4J4X9CRGE13elQI6sgGAeuMZM4OvLhRyA7SRGHBQVGF7kvAHosqlocRexO1sBtPIaO2mamr9vy80DFyUPun55YBEvjzg
Host: localhost:8080

